# .github/workflows/keep-alive.yml
name: Keep Render API Warm

# This workflow runs every 10 minutes to ping the Render API and prevent it from sleeping.
on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: |
          curl -X POST https://t20-score-predictor-8ege.onrender.com/predict \
            -H "Content-Type: application/json" \
            -d '{"batting_team":"India","bowling_team":"Australia","city":"Dubai","current_score":0,"overs":1,"wickets":0}'
